---
version: '3.8'
services:
  gateway:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - redis
    - echo
    env_file: .env
    environment:
      THREESCALE_PORTAL_ENDPOINT: http://echo:8081/config/
  echo:
    image: ${IMAGE_NAME:-apicast-test}
    environment:
      APICAST_CONFIGURATION_LOADER: test
      APICAST_MANAGEMENT_API: debug
    command: bin/apicast
    ports:
      - '8081'
  dev:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - redis
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/opt/app-root/src
    env_file: .env
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_REDIS_HOST: redis
    dns_search:
      - example.com
  test:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
      - gateway
    entrypoint: ""
    dns: 127.0.0.1
    environment:
      APICAST_MANAGEMENT_API: debug
      APICAST_LOG_LEVEL: debug
      APICAST_CONFIGURATION_LOADER: test
    dns_search:
      - example.com
  redis:
    image: mirror.gcr.io/library/redis
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KEYCLOAK_LOGLEVEL: INFO
    ports:
      - "8080"
